# Application Configuration file
# ==============================
# Contains the configuration for the application.
# Configuration information includes the default port, database information, etc

# Default Application Configuration
# ----------------------------
---
server:
  port: 8080
  url: "http://localhost:8080/admin"

routes:
  - source: /admin
    destination: www.google.com