# Application Configuration file
# ==============================
# Contains the configuration for the application.
# Configuration information includes the default port, database information, etc

# Default Application Configuration
# ----------------------------
---
server:
  port: 8080
  url: "http://localhost:8080/admin"

#[application]
#port = 8080
#adminUrl = /admin

# Mongo Database Configuration
# ----------------------------
#[database]
#host = localhost
#database = gouter